# Generated by Django 4.1.2 on 2022-12-16 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comentarios', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentarios',
        ),
    ]
