# Generated by Django 4.1.2 on 2022-12-15 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda_Coder', '0002_consolas_imagen_juegos_imagen_perifericos_imagen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consolas',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='juegos',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='perifericos',
            name='imagen',
        ),
    ]
