# Generated by Django 4.1.2 on 2022-12-15 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda_Coder', '0003_remove_consolas_imagen_remove_juegos_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perifericos',
            name='imagen',
            field=models.ImageField(blank='True', null='True', upload_to='imagen_periferico'),
            preserve_default='True',
        ),
    ]
