# Generated by Django 4.1.2 on 2022-12-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda_Coder', '0005_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
