# Generated by Django 4.1.2 on 2022-12-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda_Coder', '0006_alter_comentarios_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='imagen',
            field=models.ImageField(blank='True', null='True', upload_to='imagen_comentario'),
        ),
    ]
