# Generated by Django 4.1.2 on 2022-12-17 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda_Coder', '0007_alter_comentarios_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='consolas',
            name='imagen',
            field=models.ImageField(blank='True', null='True', upload_to='imagen_consolas'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='juegos',
            name='imagen',
            field=models.ImageField(blank='True', null='True', upload_to='imagen_juegos'),
            preserve_default='True',
        ),
    ]
