# Generated by Django 4.1.2 on 2022-12-18 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda_Coder', '0008_consolas_imagen_juegos_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='consolas',
            name='destacado',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='juegos',
            name='destacado',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perifericos',
            name='destacado',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
